### PR TITLE
update to 25.0.0.159202 with book of mercenaries enabled

### PR DESCRIPTION
**Pull request by TheGreatAthlon**

### CODE REVIEW

**Comment by TheGreatAthlon** [comment]
There is something weird going on with the adventure complete text below the hero buttons, so you probably won't  want to pull until I've fixed that.

**Comment by inkydragon** [comment]
Maybe we could ignore binary files when generate diff.

```diff
commit d21558145f00fcc773ea15a83c0c9b95a8b04c94
Author: woclass <git@wo-class.cn>
Date:   Thu Dec 1 13:30:58 2022 +0800

    rm Binary files diff

diff --git a/diff.patch b/diff.patch
index 2f14619..409c411 100644
--- a/diff.patch
+++ b/diff.patch
@@ -1,6 +1,3 @@
-diff --git a/.product.db b/.product.db
-index c6162ae..e488d2a 100644
-Binary files a/.product.db and b/.product.db differ
 diff --git a/Assembly-CSharp/.gitignore b/Assembly-CSharp/.gitignore
 new file mode 100644
 index 0000000..34c8dee
@@ -126752,84 +126749,6 @@ index 94b939b..972bf37 100644
 +
 +	#endregion
  }
-diff --git a/Hearthstone_Data/Managed/Assembly-CSharp-firstpass.dll b/Hearthstone_Data/Managed/Assembly-CSharp-firstpass.dll
-index a89ff5f..9dca7ec 100644
-Binary files a/Hearthstone_Data/Managed/Assembly-CSharp-firstpass.dll and b/Hearthstone_Data/Managed/Assembly-CSharp-firstpass.dll differ
-diff --git a/Hearthstone_Data/Managed/Assembly-CSharp.dll b/Hearthstone_Data/Managed/Assembly-CSharp.dll
-index c1aaaf9..ea656d2 100644
-Binary files a/Hearthstone_Data/Managed/Assembly-CSharp.dll and b/Hearthstone_Data/Managed/Assembly-CSharp.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.Commerce.dll b/Hearthstone_Data/Managed/Blizzard.Commerce.dll
-index 21a2e9c..9fe16ae 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.Commerce.dll and b/Hearthstone_Data/Managed/Blizzard.Commerce.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.AppsFlyer.dll b/Hearthstone_Data/Managed/Blizzard.T5.AppsFlyer.dll
-index 0b291bb..6220d22 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.AppsFlyer.dll and b/Hearthstone_Data/Managed/Blizzard.T5.AppsFlyer.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.AssetLoader.dll b/Hearthstone_Data/Managed/Blizzard.T5.AssetLoader.dll
-index 3b1bcbd..2486f8e 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.AssetLoader.dll and b/Hearthstone_Data/Managed/Blizzard.T5.AssetLoader.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.AssetManager.dll b/Hearthstone_Data/Managed/Blizzard.T5.AssetManager.dll
-index e9ea46a..8bbb07d 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.AssetManager.dll and b/Hearthstone_Data/Managed/Blizzard.T5.AssetManager.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.Configuration.dll b/Hearthstone_Data/Managed/Blizzard.T5.Configuration.dll
-index 57d8a93..21a8804 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.Configuration.dll and b/Hearthstone_Data/Managed/Blizzard.T5.Configuration.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.Core.dll b/Hearthstone_Data/Managed/Blizzard.T5.Core.dll
-index a759ccf..a42d110 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.Core.dll and b/Hearthstone_Data/Managed/Blizzard.T5.Core.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.ErrorInterface.dll b/Hearthstone_Data/Managed/Blizzard.T5.ErrorInterface.dll
-index f56b523..62b3a9c 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.ErrorInterface.dll and b/Hearthstone_Data/Managed/Blizzard.T5.ErrorInterface.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.FontService.dll b/Hearthstone_Data/Managed/Blizzard.T5.FontService.dll
-index 9f4d1d6..66f6b86 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.FontService.dll and b/Hearthstone_Data/Managed/Blizzard.T5.FontService.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.GameStringsInterface.dll b/Hearthstone_Data/Managed/Blizzard.T5.GameStringsInterface.dll
-index c473008..5a0276a 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.GameStringsInterface.dll and b/Hearthstone_Data/Managed/Blizzard.T5.GameStringsInterface.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.GraphicsManagerInterface.dll b/Hearthstone_Data/Managed/Blizzard.T5.GraphicsManagerInterface.dll
-index 5e74aa1..023ca63 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.GraphicsManagerInterface.dll and b/Hearthstone_Data/Managed/Blizzard.T5.GraphicsManagerInterface.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.JobQueue.dll b/Hearthstone_Data/Managed/Blizzard.T5.JobQueue.dll
-index 663dc97..15b3e87 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.JobQueue.dll and b/Hearthstone_Data/Managed/Blizzard.T5.JobQueue.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.Localization.dll b/Hearthstone_Data/Managed/Blizzard.T5.Localization.dll
-index 0258580..762ed48 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.Localization.dll and b/Hearthstone_Data/Managed/Blizzard.T5.Localization.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.Logging.dll b/Hearthstone_Data/Managed/Blizzard.T5.Logging.dll
-index 09c3eb0..898ec38 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.Logging.dll and b/Hearthstone_Data/Managed/Blizzard.T5.Logging.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.MaterialService.dll b/Hearthstone_Data/Managed/Blizzard.T5.MaterialService.dll
-index 2dae9c9..fd9b55b 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.MaterialService.dll and b/Hearthstone_Data/Managed/Blizzard.T5.MaterialService.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.MiniJSON.dll b/Hearthstone_Data/Managed/Blizzard.T5.MiniJSON.dll
-index 52182d9..c41aa3a 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.MiniJSON.dll and b/Hearthstone_Data/Managed/Blizzard.T5.MiniJSON.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.PlayMaker.Runtime.dll b/Hearthstone_Data/Managed/Blizzard.T5.PlayMaker.Runtime.dll
-index 307f11d..ad8434c 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.PlayMaker.Runtime.dll and b/Hearthstone_Data/Managed/Blizzard.T5.PlayMaker.Runtime.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.PlayMakerCustomActions.Runtime.dll b/Hearthstone_Data/Managed/Blizzard.T5.PlayMakerCustomActions.Runtime.dll
-index a670f2b..d0e0270 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.PlayMakerCustomActions.Runtime.dll and b/Hearthstone_Data/Managed/Blizzard.T5.PlayMakerCustomActions.Runtime.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.ServiceLocator.dll b/Hearthstone_Data/Managed/Blizzard.T5.ServiceLocator.dll
-index b6cd096..b6ba55e 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.ServiceLocator.dll and b/Hearthstone_Data/Managed/Blizzard.T5.ServiceLocator.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.UI.Core.dll b/Hearthstone_Data/Managed/Blizzard.T5.UI.Core.dll
-index 2e9b49c..eb740bf 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.UI.Core.dll and b/Hearthstone_Data/Managed/Blizzard.T5.UI.Core.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.UberText.Runtime.dll b/Hearthstone_Data/Managed/Blizzard.T5.UberText.Runtime.dll
-index d93f730..27405a8 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.UberText.Runtime.dll and b/Hearthstone_Data/Managed/Blizzard.T5.UberText.Runtime.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.T5.iTween.dll b/Hearthstone_Data/Managed/Blizzard.T5.iTween.dll
-index 317c919..5d57cd2 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.T5.iTween.dll and b/Hearthstone_Data/Managed/Blizzard.T5.iTween.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.Telemetry.Identity.dll b/Hearthstone_Data/Managed/Blizzard.Telemetry.Identity.dll
-index c94fd4c..60af985 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.Telemetry.Identity.dll and b/Hearthstone_Data/Managed/Blizzard.Telemetry.Identity.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.Telemetry.Sdk.dll b/Hearthstone_Data/Managed/Blizzard.Telemetry.Sdk.dll
-index 50c2d35..722e19e 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.Telemetry.Sdk.dll and b/Hearthstone_Data/Managed/Blizzard.Telemetry.Sdk.dll differ
-diff --git a/Hearthstone_Data/Managed/Blizzard.Telemetry.StandardProtos.BlizzPbc.dll b/Hearthstone_Data/Managed/Blizzard.Telemetry.StandardProtos.BlizzPbc.dll
-index 1424f07..56cfcdb 100644
-Binary files a/Hearthstone_Data/Managed/Blizzard.Telemetry.StandardProtos.BlizzPbc.dll and b/Hearthstone_Data/Managed/Blizzard.Telemetry.StandardProtos.BlizzPbc.dll differ
 diff --git a/Hearthstone_Data/Managed/EditorToUnityLinkerData.json b/Hearthstone_Data/Managed/EditorToUnityLinkerData.json
 index 3518896..7f10e3d 100644
 --- a/Hearthstone_Data/Managed/EditorToUnityLinkerData.json
@@ -126862,39 +126781,6 @@ index e570f34..6261302 100644
  		<type fullname="UnityEngine.AudioBehaviour" preserve="nothing"/>
  		<type fullname="UnityEngine.AudioListener" preserve="nothing"/>
  		<type fullname="UnityEngine.FlareLayer" preserve="nothing"/>
-diff --git a/Hearthstone_Data/Managed/UniTask.dll b/Hearthstone_Data/Managed/UniTask.dll
-index ff8a18e..eefc895 100644
-Binary files a/Hearthstone_Data/Managed/UniTask.dll and b/Hearthstone_Data/Managed/UniTask.dll differ
-diff --git a/Hearthstone_Data/Managed/Unity.RenderPipeline.Universal.ShaderLibrary.dll b/Hearthstone_Data/Managed/Unity.RenderPipeline.Universal.ShaderLibrary.dll
-index c601884..a02f426 100644
-Binary files a/Hearthstone_Data/Managed/Unity.RenderPipeline.Universal.ShaderLibrary.dll and b/Hearthstone_Data/Managed/Unity.RenderPipeline.Universal.ShaderLibrary.dll differ
-diff --git a/Hearthstone_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll b/Hearthstone_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll
-index fac1c92..840899d 100644
-Binary files a/Hearthstone_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll and b/Hearthstone_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll differ
-diff --git a/Hearthstone_Data/Managed/Unity.RenderPipelines.Universal.Runtime.dll b/Hearthstone_Data/Managed/Unity.RenderPipelines.Universal.Runtime.dll
-index 47c1961..4682047 100644
-Binary files a/Hearthstone_Data/Managed/Unity.RenderPipelines.Universal.Runtime.dll and b/Hearthstone_Data/Managed/Unity.RenderPipelines.Universal.Runtime.dll differ
-diff --git a/Hearthstone_Data/Managed/Unity.Timeline.dll b/Hearthstone_Data/Managed/Unity.Timeline.dll
-index 2920a1d..ebd38f8 100644
-Binary files a/Hearthstone_Data/Managed/Unity.Timeline.dll and b/Hearthstone_Data/Managed/Unity.Timeline.dll differ
-diff --git a/Hearthstone_Data/Managed/Unity.ZombieObjectDetector.Runtime.dll b/Hearthstone_Data/Managed/Unity.ZombieObjectDetector.Runtime.dll
-index 4f7024d..516813c 100644
-Binary files a/Hearthstone_Data/Managed/Unity.ZombieObjectDetector.Runtime.dll and b/Hearthstone_Data/Managed/Unity.ZombieObjectDetector.Runtime.dll differ
-diff --git a/Hearthstone_Data/Managed/UnityEngine.UI.dll b/Hearthstone_Data/Managed/UnityEngine.UI.dll
-index 32fae79..5329b16 100644
-Binary files a/Hearthstone_Data/Managed/UnityEngine.UI.dll and b/Hearthstone_Data/Managed/UnityEngine.UI.dll differ
-diff --git a/Hearthstone_Data/Managed/blizzard.bgsclient.dll b/Hearthstone_Data/Managed/blizzard.bgsclient.dll
-index f611bba..2a02835 100644
-Binary files a/Hearthstone_Data/Managed/blizzard.bgsclient.dll and b/Hearthstone_Data/Managed/blizzard.bgsclient.dll differ
-diff --git a/Hearthstone_Data/Managed/blizzard.bgssdk.dll b/Hearthstone_Data/Managed/blizzard.bgssdk.dll
-index 113b6f2..0aeb409 100644
-Binary files a/Hearthstone_Data/Managed/blizzard.bgssdk.dll and b/Hearthstone_Data/Managed/blizzard.bgssdk.dll differ
-diff --git a/Hearthstone_Data/Managed/com.blizzard.mobile-unity-auth-sdk.dll b/Hearthstone_Data/Managed/com.blizzard.mobile-unity-auth-sdk.dll
-index e03c207..b4e275c 100644
-Binary files a/Hearthstone_Data/Managed/com.blizzard.mobile-unity-auth-sdk.dll and b/Hearthstone_Data/Managed/com.blizzard.mobile-unity-auth-sdk.dll differ
-diff --git a/Hearthstone_Data/Managed/mscorlib.dll b/Hearthstone_Data/Managed/mscorlib.dll
-index bf07829..48acbfb 100644
-Binary files a/Hearthstone_Data/Managed/mscorlib.dll and b/Hearthstone_Data/Managed/mscorlib.dll differ
 diff --git a/Hearthstone_Data/Managed/response.rsp b/Hearthstone_Data/Managed/response.rsp
 index be4c9ce..30f29e3 100644
 --- a/Hearthstone_Data/Managed/response.rsp
```

**Comment by jscholes** [comment]
Current credits:

* @antonshusharin (@Endefx on Discord):
    * Substantive updates to adapt the code for Hearthstone 25.x, including merge conflict cleanup.
    * Addition of corpse counter announcements for both players.
    * Addition of rune announcements on cards outside of game play (e.g. in the collection manager).
* @TheGreatAthlon (@keyWasFull on Discord):
    * Initial Book of Mercenaries access from Modes screen.
    * Additional Book of Heroes access: Gul'Dan, Malfurion, Faelin and Illidan.
    * Fix for spectate button bug.
* @Jscholes (same Discord handle):
    * Addition of location durability and readiness announcements.

**Comment by GuideDev** [comment]
Hey everyone, thanks for all the contributions!

Few comments on the contributions so far:

1. Moving forwards, could we please open separate PRs? Say, one for fixing 25.0.0, one for adding corpse counters, etc. Having one giant PR is quite unwieldy. Remember you can (and should) simply use branches locally and rebase as needed. There's no need for all the sync up work - particularly if something ends up needing to be rolled back even though everything else is working.

2. Can we make sure localizations are kept on https://github.com/HearthstoneAccess/Localization? That repository is a submodule of this one and most of the translators are already used to contributing directly to it. There's no need to ask people for lists and go through all the work of versioning - just ask the translators to open PRs themselves and save that time to work on the codebase itself.

3. Making Book of Mercenaries and the remaining Book of Heroes available makes no sense unless they're actually accessible. I wrote code to specifically disable them because not everyone knows how to use OCR. The point being that if you do know how to use OCR (which you need to if you want to e.g. select your Hero Power and whatnot), you certainly don't need Hearthstone Access to give you a nice interface to access them.

As a general rule, a particular menu should only be accessible if (and only if) you don't need to use OCR nor external tools (e.g. GC, AHK) to play that particular game mode and/or interact with that particular UI. Remember there are tons of casual players who don't even understand how to manually patch the game. And most of these wouldn't even be on Discord.

I'll try to find some time during the weekend to run some tests once this has stabilized a bit. Thanks!

**Comment by TheGreatAthlon** [comment]
closing this for now, we will make another one with the essential52.0 fixes.

**Pull request closed without merging**
